### PR TITLE
DEV-221: extract DC from solr record

### PR DESCRIPTION
**Pull request by jsteverman**
The rights statement is still a TODO.

### CODE REVIEW

**Comment by aelkiss** [comment]
Comparing what this does (alongside https://github.com/ruby-marc/ruby-marc/blob/master/lib/marc/dublincore.rb) to the current implementation (https://hathitrust.atlassian.net/wiki/download/attachments/2174418945/MARC21slim2OAIDC.xsl), with the caveat that I don't know how much people depend on what exactly this spits out -- definitely worth asking Graham to review:

- creator seems equivalent in the XSLT and rubymarc
- type has a somewhat complicated mapping in the XSLT based on the leader. I don't know that we index that anywhere in solr (there is 'format' but that seems disjoint)
- publisher seems equivalent
- the XSLT gets language from the 008, and uses the resulting code rather than the mapped value that Solr has (I don't know if this would be an issue or not, but it's definitely a change). (Rubymarc uses only the 546, which seems like an odd choice from my uninformed perspective)
- the XSLT gets format from the 856$q, which maybe somehow gets generated as part of the OAI process? Here, it looks like we use the solr "format" field. It certainly differs, but again I don't know if that's a meaningful or impactful difference.
- the XSLT gets description from a variety of 5xx fields. I would defer to Graham on whether it would be more useful to use the 300 as you are here or whether we should use the 5xx fields.
- the XSLT gets subject from the same 6xx fields as rubymarc
- XSLT uses coverage from 752, rubymarc also includes the 651. I would imagine that's fine.
- XSLT gets relation from the same fields (530 and 760 - 787)
- XSLT gets identifier from 856$u (which ends up having the handle.net URL) as well as the 020$a (to try to get an ISBN??). It looks like we extract both handles and OCLC #s from the solr document, which seems fine. I don't know if it's valuable to continue to try to include ISBN or not (again I'd defer to Graham)
- XSLT gets rights from 506$a and 540$a which appears to be the same as rubymarc. The longer rights statements are stored in the access_stmts table and are mapped to from the rights attribute & access profile via the access_stmts_map table, but I don't know how they end up in OAI (@respinos ?)

**Review by aelkiss — COMMENTED** [review]
This is certainly much cleaner now, and generally makes sense; what I don't know is whether the behavior is actually what we want or not. It's certainly a step in the right direction and ought to produce usable output, but it's not always the same as what we're doing now, and I don't know enough of how people might use it to say whether that will make a difference or not.

**Comment by billdueber** [comment]
Just a note to say that I've talked with @jsteverman and we're definitely ignoring the ruby-marc DC stuff (at least some of which doesn't make any sense, e.g, is guaranteed to not return any data).

**Comment by aelkiss** [comment]
@billdueber @jsteverman  Where are we landing on this? Do we want to do further work on dublin core in the application? Is there a plan to address it at the rubymarc level? Either way, what's here now seems better than nothing?

**Comment by jsteverman** [comment]
I added ISBNs to the list of identifiers. 

In general, I would like to avoid MARC -> DC if we can make MARC -> Solr -> DC work. 

I added https://hathitrust.atlassian.net/browse/DEV-353 for the rights statement.

**Comment by aelkiss** [comment]
I agree with the MARC -> Solr -> DC. (It will also make producing DC output much faster if we can avoid parsing the MARC record.)

**Comment by aelkiss** [comment]
After discussing with @jsteverman  I'm going to go ahead and merge this; while it doesn't necessarily complete DEV-221, we don't really have a spec for what we need, and I'm certain it's an improvement over what's there now. We will discuss more on the 24th when everyone is back from vacation to see if we can nail down what we need to finish this one.

**Pull request merged**
