### PR TITLE
Final resumption token

### PR DESCRIPTION
**Pull request by aelkiss**
Will need to rebase once #15  is merged, but I wanted to get this up as a draft.

### CODE REVIEW

**Comment by aelkiss** [comment]
The main thing I might be worried about at this point is if the actual number of results doesn't match the expected number of results. The upgrade notes for solr 8.6 implies that prior to 8.6 result counts were always exact: https://solr.apache.org/guide/8_6/solr-upgrade-notes.html -- and we wouldn't be doing any ranking or using `minExactCount` in any case. @billdueber do you have any other insight there?

We could/should also check if the value we get for `numFound` changes between queries (implying an index change) and invalidate the resumption token in that case.

The other thing to potentially worry about is if all items are filtered off of a record that shows up in a subset query. I don't *think* that could happen unless there's a mismatch in the logic used to calculate the solr filter we're using vs. how we're filtering items (i.e. a record in the `pd` set should always have at least one item that matches the filter, and likewise for `pdus`)

**Comment by aelkiss** [comment]
This doesn't address token expiration or invalidation; I'm inclined to do that next/separately, but I could be convinced to at least do something to check that the total number of results hasn't changed.

**Comment by aelkiss** [comment]
Deploying to testing; I will try doing a daily harvest; then start a full harvest over the weekend & see if it works.

**Comment by billdueber** [comment]
Love everything about this refactor -- so happy to not have everything take an opaque `opts` argument. Feel free to merge once test harvest works.

**Pull request merged**
